// A list of all actions in the system.
export default {
  STARTUP: 'STARTUP',
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',

  SAVE_PROFILE: 'SAVE_PROFILE',

  MAP_LOCATION_REQUEST: 'MAP_LOCATION_REQUEST',
  MAP_LOCATION_RECEIVE: 'MAP_LOCATION_RECEIVE',
  MAP_LOCATION_FAILURE: 'MAP_LOCATION_FAILURE',

  MAP_JSON_REQUEST: 'MAP_JSON_REQUEST',
  MAP_JSON_RECEIVE: 'MAP_JSON_RECEIVE',
  MAP_JSON_FAILURE: 'MAP_JSON_FAILURE',

  TURNED_ON_PUSH_NOTIFICATIONS: 'TURNED_ON_PUSH_NOTIFICATIONS',
  REGISTERED_PUSH_NOTIFICATIONS: 'REGISTERED_PUSH_NOTIFICATIONS',
  SKIPPED_PUSH_NOTIFICATIONS: 'SKIPPED_PUSH_NOTIFICATIONS',
  RECEIVED_PUSH_NOTIFICATION: 'RECEIVED_PUSH_NOTIFICATION',
  SEEN_ALL_NOTIFICATIONS: 'SEEN_ALL_NOTIFICATIONS',
}
