const cities = [{ "name" : "An Giang" , "cityCode" : "VN76" },
{ "name" : "Bà Rịa - Vũng Tàu" , "cityCode" : "VN64" },
{ "name" : "Bắc Giang" , "cityCode" : "VN240" },
{ "name" : "Bắc Kạn" , "cityCode" : "VN281" },
{ "name" : "Bạc Liêu" , "cityCode" : "VN781" },
{ "name" : "Bắc Ninh" , "cityCode" : "VN241" },
{ "name" : "Bến Tre" , "cityCode" : "VN75" },
{ "name" : "Bình Định" , "cityCode" : "VN56" },
{ "name" : "Bình Dương" , "cityCode" : "VN650" },
{ "name" : "Bình Phước" , "cityCode" : "VN651" },
{ "name" : "Bình Thuận" , "cityCode" : "VN62" },
{ "name" : "Cà Mau" , "cityCode" : "VN780" },
{ "name" : "Cần Thơ" , "cityCode" : "VN710" },
{ "name" : "Cao Bằng" , "cityCode" : "VN26" },
{ "name" : "Đà Nẵng" , "cityCode" : "VN511" },
{ "name" : "Đắk Lắk" , "cityCode" : "VN500" },
{ "name" : "Đắk Nông" , "cityCode" : "VN501" },
{ "name" : "Điện Biên" , "cityCode" : "VN230" },
{ "name" : "Đồng Nai" , "cityCode" : "VN61" },
{ "name" : "Đồng Tháp" , "cityCode" : "VN67" },
{ "name" : "Gia Lai" , "cityCode" : "VN59" },
{ "name" : "Hà Giang" , "cityCode" : "VN219" },
{ "name" : "Hà Nam" , "cityCode" : "VN351" },
{ "name" : "Hà Nội" , "cityCode" : "VN4" },
{ "name" : "Hà Tĩnh" , "cityCode" : "VN39" },
{ "name" : "Hải Dương" , "cityCode" : "VN320" },
{ "name" : "Hải Phỏng" , "cityCode" : "VN31" },
{ "name" : "Hậu Giang" , "cityCode" : "VN711" },
{ "name" : "Hòa Bình" , "cityCode" : "VN218" },
{ "name" : "Hồ Chí Minh" , "cityCode" : "VN8" },
{ "name" : "Hưng Yên" , "cityCode" : "VN321" },
{ "name" : "Khánh Hoà" , "cityCode" : "VN58" },
{ "name" : "Kiên Giang" , "cityCode" : "VN77" },
{ "name" : "Kon Tum" , "cityCode" : "VN60" },
{ "name" : "Lai Châu" , "cityCode" : "VN231" },
{ "name" : "Lâm Đồng" , "cityCode" : "VN63" },
{ "name" : "Lạng Sơn" , "cityCode" : "VN25" },
{ "name" : "Lào Cai" , "cityCode" : "VN20" },
{ "name" : "Long An" , "cityCode" : "VN72" },
{ "name" : "Nam Định" , "cityCode" : "VN350" },
{ "name" : "Nghệ An" , "cityCode" : "VN38" },
{ "name" : "Ninh Bình" , "cityCode" : "VN30" },
{ "name" : "Ninh Thuận" , "cityCode" : "VN68" },
{ "name" : "Phú Thọ" , "cityCode" : "VN210" },
{ "name" : "Phú Yên" , "cityCode" : "VN57" },
{ "name" : "Quảng Bình" , "cityCode" : "VN52" },
{ "name" : "Quảng Nam" , "cityCode" : "VN510" },
{ "name" : "Quảng Ngãi" , "cityCode" : "VN55" },
{ "name" : "Quảng Ninh" , "cityCode" : "VN33" },
{ "name" : "Quảng Trị" , "cityCode" : "VN53" },
{ "name" : "Sóc Trăng" , "cityCode" : "VN79" },
{ "name" : "Sơn La" , "cityCode" : "VN22" },
{ "name" : "Tây Ninh" , "cityCode" : "VN66" },
{ "name" : "Thái Bình" , "cityCode" : "VN36" },
{ "name" : "Thái Nguyên" , "cityCode" : "VN280" },
{ "name" : "Thanh Hoá" , "cityCode" : "VN37" },
{ "name" : "Thừa Thiên - Huế" , "cityCode" : "VN54" },
{ "name" : "Tiền Giang" , "cityCode" : "VN73" },
{ "name" : "Trà Vinh" , "cityCode" : "VN74" },
{ "name" : "Tuyên Quang" , "cityCode" : "VN27" },
{ "name" : "Vĩnh Long" , "cityCode" : "VN70" },
{ "name" : "Vĩnh Phúc" , "cityCode" : "VN211" },
{ "name" : "Yên Bái" , "cityCode" : "VN29" }]

export default cities