const cities = [
	{ "name" : "An Giang" , "cityCode" : "VN76" , "countryCode": "VN"},
	{ "name" : "Bà Rịa - Vũng Tàu" , "cityCode" : "VN64" , "countryCode": "VN"},
	{ "name" : "Bắc Giang" , "cityCode" : "VN240" , "countryCode": "VN"},
	{ "name" : "Bắc Kạn" , "cityCode" : "VN281" , "countryCode": "VN"},
	{ "name" : "Bạc Liêu" , "cityCode" : "VN781" , "countryCode": "VN"},
	{ "name" : "Bắc Ninh" , "cityCode" : "VN241" , "countryCode": "VN"},
	{ "name" : "Bến Tre" , "cityCode" : "VN75" , "countryCode": "VN"},
	{ "name" : "Bình Định" , "cityCode" : "VN56" , "countryCode": "VN"},
	{ "name" : "Bình Dương" , "cityCode" : "VN650" , "countryCode": "VN"},
	{ "name" : "Bình Phước" , "cityCode" : "VN651" , "countryCode": "VN"},
	{ "name" : "Bình Thuận" , "cityCode" : "VN62" , "countryCode": "VN"},
	{ "name" : "Cà Mau" , "cityCode" : "VN780" , "countryCode": "VN"},
	{ "name" : "Cần Thơ" , "cityCode" : "VN710" , "countryCode": "VN"},
	{ "name" : "Cao Bằng" , "cityCode" : "VN26" , "countryCode": "VN"},
	{ "name" : "Đà Nẵng" , "cityCode" : "VN511" , "countryCode": "VN"},
	{ "name" : "Đắk Lắk" , "cityCode" : "VN500" , "countryCode": "VN"},
	{ "name" : "Đắk Nông" , "cityCode" : "VN501" , "countryCode": "VN"},
	{ "name" : "Điện Biên" , "cityCode" : "VN230" , "countryCode": "VN"},
	{ "name" : "Đồng Nai" , "cityCode" : "VN61" , "countryCode": "VN"},
	{ "name" : "Đồng Tháp" , "cityCode" : "VN67" , "countryCode": "VN"},
	{ "name" : "Gia Lai" , "cityCode" : "VN59" , "countryCode": "VN"},
	{ "name" : "Hà Giang" , "cityCode" : "VN219" , "countryCode": "VN"},
	{ "name" : "Hà Nam" , "cityCode" : "VN351" , "countryCode": "VN"},
	{ "name" : "Hà Nội" , "cityCode" : "VN4" , "countryCode": "VN"},
	{ "name" : "Hà Tĩnh" , "cityCode" : "VN39" , "countryCode": "VN"},
	{ "name" : "Hải Dương" , "cityCode" : "VN320" , "countryCode": "VN"},
	{ "name" : "Hải Phỏng" , "cityCode" : "VN31" , "countryCode": "VN"},
	{ "name" : "Hậu Giang" , "cityCode" : "VN711" , "countryCode": "VN"},
	{ "name" : "Hòa Bình" , "cityCode" : "VN218" , "countryCode": "VN"},
	{ "name" : "Hồ Chí Minh" , "cityCode" : "VN8" , "countryCode": "VN"},
	{ "name" : "Hưng Yên" , "cityCode" : "VN321" , "countryCode": "VN"},
	{ "name" : "Khánh Hoà" , "cityCode" : "VN58" , "countryCode": "VN"},
	{ "name" : "Kiên Giang" , "cityCode" : "VN77" , "countryCode": "VN"},
	{ "name" : "Kon Tum" , "cityCode" : "VN60" , "countryCode": "VN"},
	{ "name" : "Lai Châu" , "cityCode" : "VN231" , "countryCode": "VN"},
	{ "name" : "Lâm Đồng" , "cityCode" : "VN63" , "countryCode": "VN"},
	{ "name" : "Lạng Sơn" , "cityCode" : "VN25" , "countryCode": "VN"},
	{ "name" : "Lào Cai" , "cityCode" : "VN20" , "countryCode": "VN"},
	{ "name" : "Long An" , "cityCode" : "VN72" , "countryCode": "VN"},
	{ "name" : "Nam Định" , "cityCode" : "VN350" , "countryCode": "VN"},
	{ "name" : "Nghệ An" , "cityCode" : "VN38" , "countryCode": "VN"},
	{ "name" : "Ninh Bình" , "cityCode" : "VN30" , "countryCode": "VN"},
	{ "name" : "Ninh Thuận" , "cityCode" : "VN68" , "countryCode": "VN"},
	{ "name" : "Phú Thọ" , "cityCode" : "VN210" , "countryCode": "VN"},
	{ "name" : "Phú Yên" , "cityCode" : "VN57" , "countryCode": "VN"},
	{ "name" : "Quảng Bình" , "cityCode" : "VN52" , "countryCode": "VN"},
	{ "name" : "Quảng Nam" , "cityCode" : "VN510" , "countryCode": "VN"},
	{ "name" : "Quảng Ngãi" , "cityCode" : "VN55" , "countryCode": "VN"},
	{ "name" : "Quảng Ninh" , "cityCode" : "VN33" , "countryCode": "VN"},
	{ "name" : "Quảng Trị" , "cityCode" : "VN53" , "countryCode": "VN"},
	{ "name" : "Sóc Trăng" , "cityCode" : "VN79" , "countryCode": "VN"},
	{ "name" : "Sơn La" , "cityCode" : "VN22" , "countryCode": "VN"},
	{ "name" : "Tây Ninh" , "cityCode" : "VN66" , "countryCode": "VN"},
	{ "name" : "Thái Bình" , "cityCode" : "VN36" , "countryCode": "VN"},
	{ "name" : "Thái Nguyên" , "cityCode" : "VN280" , "countryCode": "VN"},
	{ "name" : "Thanh Hoá" , "cityCode" : "VN37" , "countryCode": "VN"},
	{ "name" : "Thừa Thiên - Huế" , "cityCode" : "VN54" , "countryCode": "VN"},
	{ "name" : "Tiền Giang" , "cityCode" : "VN73" , "countryCode": "VN"},
	{ "name" : "Trà Vinh" , "cityCode" : "VN74" , "countryCode": "VN"},
	{ "name" : "Tuyên Quang" , "cityCode" : "VN27" , "countryCode": "VN"},
	{ "name" : "Vĩnh Long" , "cityCode" : "VN70" , "countryCode": "VN"},
	{ "name" : "Vĩnh Phúc" , "cityCode" : "VN211" , "countryCode": "VN"},
	{ "name" : "Yên Bái" , "cityCode" : "VN29" , "countryCode": "VN"}, 
]

export default cities